#!/usr/bin/env sh

# Sanity tests
cd "test"

cd "synch"
ln -s ../../examples/simpleclient/NetClient.tla
ln -s ../../lib/NetChannel.tla
ln -s ../../lib/SynchLib.tla
cd ".."

cd "asynch"
ln -s ../../examples/simpleclient/NetClient.tla
ln -s ../../lib/NetChannel.tla
ln -s ../../lib/AsynchLib.tla
cd ".."

cd "partial"
ln -s ../../examples/simpleclient/NetClient.tla
ln -s ../../lib/NetChannel.tla
ln -s ../../lib/PartialLib.tla
cd ".."

cd ".."

# Library usage examples
cd "examples"

cd "twophase"
ln -s ../../lib/NetChannel.tla
ln -s ../../lib/SynchLib.tla
cd ".."

cd ".."
